@startuml general
hide empty members

interface IDatosDelJuego
{
    + getItems() : IListaItems
    + getLadrones() : IListaLadrones
    + getCiudades() : IMapaCiudades
    + getPistas() : IListaPistas
    + getPolicias() : IListaPolicias
    + guardarTodo()
    + recargarTodo()
}
class DatosDelJuego implements IDatosDelJuego
{
    + DatosDelJuego(directorio:String)
    + getItems() : IListaItems
    + getLadrones() : IListaLadrones
    + getCiudades() : IMapaCiudades
    + getPistas() : IListaPistas
    + getPolicias() : IListaPolicias
    + guardarTodo()
    + recargarTodo()
    + recargarTodoDesde(directorio:String)
}
DatosDelJuego "1" *-- "1" IListaPolicias
interface IListaPolicias {
    + agregar(agente:Policia)
    + borrar(agente:Policia)
    + getPorNombre(nombre:String):Policia
    + guardar()
    + recargar()
}
DatosDelJuego "1" *-- "1" IListaItems
interface IListaItems {
    + getTodos():IList<Item>
    + guardar()
    + recargar()
}
DatosDelJuego "1" *-- "1" IListaLadrones
interface IListaLadrones {
    + getTodos():IList<Ladron>
    + guardar()
    + recargar()
}
DatosDelJuego "1" *-- "1" IListaPistas
interface IListaPistas {
    + getPistaLadron(ladron:Ladron):IList<IPista>
    + getPistaPais(ciudad:Ciudad):IList<IPista>
    + getTodas():IList<IPista>
    + getTodas():IList<IPista>
    + guardar()
    + recargar()
}
DatosDelJuego "1" *-- "1" IMapaCiudades
interface IMapaCiudades {
    + getDistancia(desde:string,hasta:string):Number
    + getPorNombre(nombre:String):Ciudad
    + getTodas():IList<Ciudad>
    + guardar()
    + recargar()
}
@enduml