@startuml general
hide empty members
skinparam nodesep 50
skinparam ranksep 60
hide empty members
skinparam minClassWidth 100

package TP3 {
    together {
        class XXXX_A {}
        class XXXX_B extends XXXX_A {}
    }
    together {
        interface IXXXX {}
        class XXXX_C implements IXXXX {}
        class XXXX_D implements IXXXX {}
        class XXXX_E implements IXXXX {}
    }
    XXXX_A "*" *-> "1" IXXXX
    XXXX_E "*" *-> "1" IXXXX
    XXXX_P ..> XXXX_A
    XXXX_P ..> XXXX_B
    XXXX_P ..> IXXXX
}
@enduml

